l seek 5
h seek -5

L add audio-delay 0.100
H add audio-delay -0.100

ctrl+u seek 30
ctrl+d seek -30

k multiply speed 1.1
j multiply speed 1/1.1

n playlist-next
p playlist-prev

ctrl+r revert-seek

u add volume 2
d add volume -2

ctrl+a add video-zoom 0.1
ctrl+x add video-zoom -0.1

f cycle fullscreen
# v cycle video
m cycle mute
SPACE cycle pause
s cycle shuffle
A cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "no"

# TODO: check how to enable repeat a video current it is automatic
# r cycle repeat
q quit
