; Headless or minimal interface
idle=yes
terminal

; Output
vo=gpu
hwdec=auto
profile=fast

; Audio
audio-device=auto

; Video
fullscreen=no
keepaspect=yes

; Playlist behavior
loop=inf
shuffle=no

; Subtitles
sub-auto=exact

; others
screenshot-dir=~/screenshots/

; Enable JSON IPC for scripting
input-ipc-server=/tmp/mpvsocket
