[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super"

[colors.bright]
black = "#6272a4"
blue = "#6699cc"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92df"
red = "#ff6e67"
white = "#ffffff"
yellow = "#f4f99d"

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#e0def4"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.normal]
black   = "#1A1A1A"  # softened black (not crushing details)
red     = "#FF4C4C"  # vibrant but not eye-searing
green   = "#4CFF4C"  # clean green with balance
yellow  = "#FFD64C"  # golden yellow, less neon than pure
blue    = "#4C6FFF"  # slightly softened pure blue
magenta = "#FF4CFF"  # bright magenta, but not full neon
cyan    = "#4CFFFF"  # aqua cyan, easy on eyes
white   = "#E6E6E6"  # soft white, avoids #FFFFFF glare

[colors.primary]
foreground = "#e0def4"
# background = "#0E0B00"  # my original color (near black with faint brown)
# background = "#16120B"  # softer, transparent-like brownish black
background = "#1A1510"  # dark coffee brown, slightly warmer
# background = "#1C1812"  # muted sepia black, blends well with rose-pine
# background = "#201A14"  # earthy cocoa brown, still very dark
# background = "#241C16"  # warm shadow brown, a bit richer

[colors.selection]
background = "#44475a"
text = "#f8f8f2"

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = false
vi_mode_style = { shape = "Beam", blinking = "On" }
thickness = 0.15

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.95

[window.padding]
x = 0
y = 0
